# In ".toml" files (NOT ".md" files) lines starting with a hashtag are comments.

# You can edit any file in the folder named "data", as well as this one. Make
# sure to follow the file format carefully. Make sure there are no missing
# punctuation marks or other syntactic elements. If any of these errors are
# present, the site will fail to build and the site will not update. If you do
# not notice the site updating within 5-10 minutes, try to find an error.

# If you want to include a new line in some text, make sure to use "<br />".

# For this, put "<p>" before each paragraph, and "</p>" afterwards.
legal = """
<p>
Notary Shop is a trading name of Notary ABC Limited. Notary services are
provided by Dermot Winters, a registered Notary Public of England and Wales.
</p>

<p>
Copyright © 2022 Notary ABC Limited.
</p>
"""

[brand]
name = "Notary Shop UK"

[contact]
address = """
Business Central <br />
2 Union Square <br />
Central Park <br />
Darlington <br />
DL1 1GL
"""
email = "enquiries@notaryshop.co.uk"
email-uri = "mailto:enquiries@notaryshop.co.uk" # if you update "email", update this
open = "Mon-Fri 8.00am until 6.00pm"
phone = "(+44) 07510 729 503"
phone-uri = "tel:+44-7510-729-503" # if you update "phone", update this

[map]
title = "How to find us"
lon = 54.5236438
lat = -1.544663
